name: Build and Publish Library

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish
        run: ./gradlew clean build

      - name: Upload to GitHub Packages
        run: ./gradlew publish
        env:
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}
